### ISSUE TITLE
Secrets Mangement using dotenv

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-movies#10]
Implement Python dotenv library to manage secrets in your django app.

- [x] https://pypi.org/project/python-dotenv/
- [x] Use secrets to store your API secrets that should not be pushed to github

Please ignore/close this task if you prefer to manage secrets differently. 
If so, please document how you will manage secrets as a comment here.

**Comment by kjcioffi** [comment]
Making use of https://django-environ.readthedocs.io/en/latest/ for secret management.

https://pypi.org/project/django-environ/
