### ISSUE TITLE
Check for success status to validate a successful test.

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-movies#15]
To make this test more robust, it might be worthwhile to ensure there are no errors. 
When I ran this test it passed successfully - which I expected to fail since I don't have the API key set yet.
Here is the resolve of self.movies_in_context: `{'status_code': 7, 'status_message': 'Invalid API key: You must be granted a valid key.', 'success': False}`

So how can you 1: make the test more robust? 
Does it make sense to test a scenario where there is no API key (success: False)?

_Originally posted by @ryaustin in https://github.com/kjcioffi/django-movies/pull/14#discussion_r1633886932_

**Comment by kjcioffi** [comment]
The movie API utility module was refactored with logic added to the test suite to provide coverage.
