### ISSUE TITLE
Verify your mindmap for the MVP

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-movies#2]
What models will you create in this mvp?
What pages do you want in this mvp?
What is the core functionality of the MVP?

Using the mindmap in your portfolio assessment think about the potential movie model. 

**What fields do you need to store?** 
- the fields you choose to store will probably have something to do with the value-added benefit of your app such as tracking a user rating or how many users have searched for this movie.

<img width="1347" alt="image" src="https://github.com/kjcioffi/django-movies/assets/4359874/cc1f5d8d-961e-4f0b-b7be-77d2e2f9de56">

**Comment by ryaustin** [comment]
Index or main view (lists automatically all movies in theaters)
- - is this a list view, is it a magazine view, do we show thumbnails, what columns are displayed
- clicking any of the movies displays the detailed view

**Comment by kjcioffi** [comment]
![Movies In Theater Mind Map](https://github.com/kjcioffi/django-movies/assets/11459552/7bd0567d-9af9-4989-88c8-cdeb25a81fad)
