### ISSUE TITLE
Fix released on date in template

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-movies#24]
Take a look at the template filter used on the release_date attribute in the movie_list template. 
The released on value is not being rendered on the frontend

<img width="377" alt="Screenshot 2024-06-18 at 12 13 29 PM" src="https://github.com/kjcioffi/django-movies/assets/4359874/08950b2b-b4db-45a7-84df-bba053fd6d62">

**Comment by kjcioffi** [comment]
Created PR #25 to resolve the issue.
