### ISSUE TITLE
Build the movie detail page

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-movies#8]
This page should display additional details about the movie as displayed in your mindmap design.

*key note - don't worry so much about CSS and graphics if that is not your thing, we can work on making it pretty.

**Comment by kjcioffi** [comment]
Facing a design issue I could use some help with, @ryaustin.

I'm focusing on implementing exception handling, part of which I'm finding needs to be included in the view. 

Referencing the _get method in the movie_api_utils module raises a custom MovieApiException on almost all accounts. Would you suggest looking into exceptions from the **requests** library corresponding to 404 and 500s HTTP responses to instead raise Django-related exceptions in the method?

From _get method:

       `except requests.exceptions.HTTPError:
            raise MovieApiException("Failed to retrieve data from the movie database.")
        except requests.exceptions.ConnectionError:
            raise MovieApiException(
                "Network connection error occurred while accessing the movie database."
            )
        except requests.exceptions.Timeout:
            raise MovieApiException("Request to the movie database timed out.")
        except requests.exceptions.RequestException:
            raise MovieApiException("An error occurred while processing your request.")`

**Comment by ryaustin** [comment]
Hmm, I do see where the exception raised by the _get method might not be ideal in some cases.
You should definitely design your exception handling with thoughtfulness in mind - that is to say, what would you like to see returned in specific cases. Some things to consider:

- Sometimes, its worth passing the error straight through so that the developer who does not care about the internals of your wrapper can do their own exception handling in the view.
- While it's possible to map these exceptions to Django-related exceptions, it's generally more maintainable to keep your custom exceptions and handle them appropriately in your views. This way, your exception-handling logic remains decoupled from Django's specific implementation, (also making it easier to manage and potentially reuse outside of Django.)

So my thought here is to go with your gut, there is no right or wrong and arguments can always be made for the best way. Ultimately the goal is to make your code readable, and maintainable.

**Comment by kjcioffi** [comment]
PRs #29 and #30 will complete this issue.
