### ISSUE TITLE
Using requests & GraphQL

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-movies#9]
To access the imdb api,  you need to craft graphQL queries as the API does not accept the typical rest queries commonly found on the web.

- [ ] Read the following article to learn how to use graphQL using the requests library in python: https://www.geeksforgeeks.org/get-and-post-requests-in-graphql-api-using-python-requests/

**Comment by kjcioffi** [comment]
I realized the IMDb API has a $150k price tag.

**Comment by kjcioffi** [comment]
While I could access it with a one-month free trial, I have decided to pivot to a different API, one hosted by https://www.themoviedb.org/

**Comment by ryaustin** [comment]
Dang! That's a lot of mullah.
Your first pivot on this project. 👍

**Comment by kjcioffi** [comment]
Yes! It would've been nice to use IMDb, I was excited to learn GraphQL 😎
